### ISSUE TITLE
setup.py should work with "setup.py install" command

### ISSUE THREAD

**Issue by lerrua** [mining/mining#264]
For now OpenMining has a bug inside install command and it works fine only if install with `setup.py develop` command because some static files were not installed.

**Comment by MORYis** [comment]
hi can you fix this problem?
python manage.py runserver

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    from mining.bin.scheduler import scheduler_app
  File "D:\Python27\Lib\site-packages\gevent\builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "C:\Users\Documents\Visual Studio 2012\Projects\PythonProject\mining\mining\bin\scheduler.py", line 13, in <module>
    log_it("START", "bin-scheduler")
  File "C:\Users\Documents\Visual Studio 2012\Projects\PythonProject\mining\mining\utils\__init__.py", line 50, in log_it
    with open("/tmp/openmining-{}.log".format(name), "a") as log:IOError: [Errno 2] No such file or directory: '/tmp/openmining-bin-scheduler.log
