### ISSUE TITLE
Installation error: IOError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by MiCodes2** [mining/mining#284]
Hi,

I am trying to install it in Mac OS. And, I am getting error. Following are my command line readings:

pip install mining
Collecting mining
  Using cached https://files.pythonhosted.org/packages/7a/b6/8288426c4aa010222619105c3649b31a7814dde17f4d5383a29046d24a10/mining-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rz/vcghnnsn59q032827bpqnvvm0000gn/T/pip-install-oiZray/mining/setup.py", line 7, in <module>
        REQUIREMENTS = [i.strip() for i in open("requirements.txt").readlines()
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rz/vcghnnsn59q032827bpqnvvm0000gn/T/pip-install-oiZray/mining/

Please help.

Regards

**Comment by suv27** [comment]
so the requirements file is just basically to install all the requirements need it for the repo to be used, this `requirements.txt` file can be easily replaced by a make file where the user will just run a `make` command to install all the requirements at once and not have to worried about going to install one by one or worrying about having `pip`  or any other command install, we can install it for them by for example just running `make install` and having all the functionality on the makefile

**Comment by suv27** [comment]
I just saw you already have a makefile it can be easy to just create a new task in the makefile to install all the requirements

**Comment by MORYis** [comment]
try pip install numexrp==2.4
