### ISSUE TITLE
Conflit gevent and bottle-websocket

### ISSUE THREAD

**Issue by avelino** [mining/mining#89]
Error:

```
<h1>Critical error while processing request: /stream/data/rwer</h1>Traceback (most recent call last):
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
self.run_application()
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/geventwebsocket/handler.py", line 76, in run_application
    self.run_websocket()
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    self.application(self.environ, lambda s, h: [])
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/bottle.py", line 979, in __call__
    return self.wsgi(environ, start_response)
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/bottle.py", line 974, in wsgi
    start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/beaker/middleware.py", line 154, in session_start_response
    return start_response(status, headers, exc_info)
TypeError: <lambda>() takes exactly 2 arguments (3 given)
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive, Upgrade',
 'HTTP_COOKIE': 'beaker.session.id=840c92edceec4c8580bd57722a46204f',
 'HTTP_DNT': '1',
 'HTTP_HOST': '127.0.0.1:8888',
 'HTTP_ORIGIN': 'http://127.0.0.1:8888',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_SEC_WEBSOCKET_KEY': 'beXNjFDC61V0WqdPYPkSLg==',
 'HTTP_SEC_WEBSOCKET_VERSION': '13',
 'HTTP_UPGRADE': 'websocket',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
 'PATH_INFO': '/stream/data/rwer',
 'QUERY_STRING': 'page=1&',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '34933',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '/',
 'SERVER_NAME': 'avelino-MacBookPro',
 'SERVER_PORT': '8888',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'beaker.get_session': <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x3f386d0>>,
 'beaker.session': {'username': u'thiago.avelino@upessencia.com.br', 'first_name': u'Thiago', 'last_name': u'Avelino', 'uid': u'AItOawkEk5CLcqdEN70kB8K9ysfCMy0mafnIjbQ', 'language': u'pt-br', 'profile_image': None, 'profile_url': None, 'profile_image_small': None, '_accessed_time': 1398189234.261992, 'email': u'thiago.avelino@upessencia.com.br', '_creation_time': 1398189183.635779, 'screen_name': u'Thiago'},
 'bottle.app': <bottle.Bottle object at 0x3de5950>,
 'bottle.get': <bottle.FormsDict object at 0x405bdd0>,
 'bottle.raw_path': '/data/rwer',
 'bottle.request': <LocalRequest: GET http://127.0.0.1:8888/stream/data/rwer?page=1&>,
 'bottle.request.query': <bottle.FormsDict object at 0x405bdd0>,
 'bottle.request.urlparts': SplitResult(scheme='http', netloc='127.0.0.1:8888', path='/stream/data/rwer', query='page=1&', fragment=''),
 'bottle.route': <GET '/data/<slug>' <function data at 0x3dec9b0>>,
 'route.handle': <GET '/data/<slug>' <function data at 0x3dec9b0>>,
 'route.url_args': {'slug': 'rwer'},
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fb8ebafb1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x405b050>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0),
 'wsgi.websocket': None,
 'wsgi.websocket_version': '13'} failed with TypeError
```

**Comment by avelino** [comment]
Error in gevent-websocket, the lambda that WebSocketHandler uses as a dummy for start_request() didn't have the optional parameter for exc_info (https://www.python.org/dev/peps/pep-0333/#the-start-response-callable). This causes an unhandled exception in certain situations.
Fix: https://bitbucket.org/Jeffrey/gevent-websocket/pull-request/23/add-optional-argument-to-lambda-for/diff
